// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)"
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

#[path = "gethostlatency.skel.rs"]
mod gethostlatency_skel;

pub use gethostlatency_skel::*;
